#:schema https://www.unpkg.com/wrangler/config-schema.json

compatibility_date = "2025-11-20"
compatibility_flags = ["nodejs_compat"]
main = "./src/index.ts"
minify = true
name = "telegram-bot"
send_metrics = false
upload_source_maps = true

[observability]
enabled = true

[placement]
mode = "smart"
